import { DecorativeStripes, DecorativeStripesRight } from "@/shared/ui/decorative-stripes";

const TermsPage = () => {
  return (
    <section className="w-full bg-white">
      <div className="flex">
        <DecorativeStripes />

        <div className="flex-1 border-x border-slate-200 py-16 lg:py-24 px-4 sm:px-6 lg:px-8">
          <div className="max-w-7xl mx-auto">
            <div className="mx-auto">
        <h1 className="text-5xl font-extrabold mb-4 ai-robotic-gradient">Terms of Service</h1>
        <p className="text-slate-500 mb-12 font-medium">Last updated: January 26, 2026</p>

        <div className="prose prose-slate lg:prose-lg max-w-none space-y-12 text-slate-700">
          <div className="p-6 bg-amber-50 rounded-2xl border border-amber-200 text-amber-900 text-sm mb-12">
            <strong>Important Notice:</strong> These terms govern your use of the AgentKit platform.
            By using our services, you acknowledge that you are interacting with AI agents that may
            produce unpredictable results.
          </div>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-6">1. Usage Rights & Licenses</h2>
            <p>
              Subject to these Terms, AgentKit grants you a non-exclusive, non-transferable license
              to use the platform for your internal business operations.
            </p>
            <div className="mt-4 p-4 bg-slate-50 rounded-xl">
              <p className="font-bold text-slate-900 mb-2">Ownership of Outputs</p>
              <p className="text-sm">
                As between you and AgentKit, you own all inputs you provide and all outputs
                generated by the agents, provided you comply with these terms and pay all applicable
                fees.
              </p>
            </div>
          </section>

          <section id="pricing-policy" className="scroll-mt-24">
            <h2 className="text-2xl font-bold text-slate-900 mb-6 flex items-center gap-3">
              <span className="size-8 rounded-lg bg-emerald-100 text-emerald-700 flex items-center justify-center text-sm">
                $
              </span>
              Pricing & Billing (Price Policy)
            </h2>
            <p className="mb-6">
              Our pricing is designed to be transparent and scale with your needs. By subscribing to
              a plan, you agree to the following:
            </p>
            <div className="space-y-4">
              <div className="p-6 border border-slate-100 rounded-2xl bg-white shadow-sm">
                <h3 className="font-bold text-slate-900 mb-2">Subscription Tiers</h3>
                <p className="text-sm">
                  We offer various monthly and annual subscription plans. Features, agent limits,
                  and token quotas vary by plan. You can upgrade or downgrade at any time.
                </p>
              </div>
              <div className="p-6 border border-slate-100 rounded-2xl bg-white shadow-sm">
                <h3 className="font-bold text-slate-900 mb-2">Refund Policy</h3>
                <p className="text-sm">
                  We offer a 14-day &quot;No Questions Asked&quot; refund policy for new subscriptions. After
                  14 days, fees are generally non-refundable except as required by law.
                </p>
              </div>
              <div className="p-6 border border-slate-100 rounded-2xl bg-white shadow-sm">
                <h3 className="font-bold text-slate-900 mb-2">Credit Usage</h3>
                <p className="text-sm">
                  Certain advanced models or operations may consume &quot;Agent Credits.&quot; If your credits
                  run out, your agents may stop functioning until the next billing cycle or top-up.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-6">2. Acceptable Use</h2>
            <p>You agree not to use the platform to:</p>
            <ul className="grid md:grid-cols-2 gap-4 list-none pl-0 mt-3">
              <li className="p-3 bg-red-50 text-red-900 rounded-lg text-sm border border-red-100">
                Generate illegal or harmful content.
              </li>
              <li className="p-3 bg-red-50 text-red-900 rounded-lg text-sm border border-red-100">
                Attempt to reverse engineer the orchestration engine.
              </li>
              <li className="p-3 bg-red-50 text-red-900 rounded-lg text-sm border border-red-100">
                Spam or harass users via automated agents.
              </li>
              <li className="p-3 bg-red-50 text-red-900 rounded-lg text-sm border border-red-100">
                Expose the platform to viruses or malicious code.
              </li>
            </ul>
          </section>

          <section className="border-t border-slate-100 pt-12">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">Disclaimers</h2>
            <p className="italic">
              AGENTKIT IS PROVIDED &quot;AS IS.&quot; WE DO NOT GUARANTEE THE ACCURACY OF AI OUTPUTS. YOU ARE
              RESPONSIBLE FOR VERIFYING ALL INFORMATION GENERATED BY THE PLATFORM BEFORE TAKING
              ACTION.
            </p>
          </section>
            </div>
          </div>
          </div>
        </div>

        <DecorativeStripesRight />
      </div>
    </section>
  );
};

export default TermsPage;
