# syntax=docker.io/docker/dockerfile:1

FROM node:22-alpine AS base

# Step 1. Rebuild the source code only when needed
FROM base AS builder

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
# Omit --production flag for TypeScript devDependencies
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
  # Allow install without lockfile, so example works even without Node.js installed locally
  else echo "Warning: Lockfile not found. It is recommended to commit lockfiles to version control." && yarn install; \
  fi

COPY . .

# Environment variables
ARG NEXT_PUBLIC_API_AUTH_URL
ARG NEXT_PUBLIC_API_ROOT_URL
ENV NEXT_PUBLIC_API_AUTH_URL=$NEXT_PUBLIC_API_AUTH_URL
ENV NEXT_PUBLIC_API_ROOT_URL=$NEXT_PUBLIC_API_ROOT_URL

# Build Next.js based on the preferred package manager
RUN \
  if [ -f yarn.lock ]; then yarn build; \
  elif [ -f package-lock.json ]; then npm run build; \
  elif [ -f pnpm-lock.yaml ]; then pnpm build; \
  else npm run build; \
  fi

# Note: It is not necessary to add an intermediate step that does a full copy of `node_modules` here

# Step 2. Production image, copy all the files and run next
FROM base AS runner

WORKDIR /app

# Create a non-root user
ARG UID=1001
ARG GID=1001

RUN getent group $GID || addgroup --gid $GID nextjs \
  && adduser --disabled-password --gecos "" --uid $UID --gid $GID --home /home/nextjs --shell /bin/bash nextjs \
  && chown -R $UID:$GID /app

# Set the user for the container
USER nextjs

COPY --from=builder --chown=nextjs:nextjs /app/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nextjs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nextjs /app/.next/static ./.next/static

# Environment variables
ARG NEXT_PUBLIC_API_AUTH_URL
ARG NEXT_PUBLIC_API_ROOT_URL
ENV NEXT_PUBLIC_API_AUTH_URL=$NEXT_PUBLIC_API_AUTH_URL
ENV NEXT_PUBLIC_API_ROOT_URL=$NEXT_PUBLIC_API_ROOT_URL

EXPOSE 3000

CMD ["node", "server.js"]
